export interface AtmStatus {
  id: number
  atm_id: number
  is_Horas_ofline: number
  is_Hora_slepping: number
  is_Horas_online: number
  last_transaction_data: string
  estado: string
  estado_papel: number
  error_description_papel: string
  error_text_papel: string
  bg_color_papel: string
  estado_cartao: number
  error_description_cartao: string
  error_text_cartao: string
  estado_dinheiro: number
  valor_actual: number
  error_text_dinheiro: string
  bg_color_dinheiro: string
  description_dinheiro: string
  info_emis: string
  estado_tecnico: number
  error_text_tecnico: string
  bg_color_tecnico: string
  icone_tecnico: string
  description_tecnico: string
  created_at: string
  updated_at: string
  rsv1: string
  rsv2: string
  rsv3: string
  rsv4: string
  rsv5: string
  rsv6: string
  rsv7: string
  rsv8: string
  rsv9: string
  rsv10: string
  bg_color_cartao: string
  current_datatime: string
}